inhibitor1217/coffee-hmm

- services/auth/src/routes/user/index.test.ts
- services/auth/src/routes/user/user.control.ts
> (#38) fix bug that 500 was thrown when fetching a nonexistent user's policy

- services/auth/README.md
- services/auth/src/routes/auth.control.ts
- services/auth/src/routes/index.test.ts
- services/auth/src/routes/index.ts
> Implement new endpoint: GET /me

- app/src/components/pages/Intro/index.tsx
- app/src/utils/type.tsx
- 카페 등록한 `creator` 표시
- creator 정보는 카페 정보 > metadata > creator 에 저장
- 제가 직접 등록한 카페들은 수가 많아서 DB에서 직접 작업 부탁드립니다ㅜ
- undefined 인 경우 jyuunnii 로 표시
> feat: 카페 creator 표시

- services/http-api/README.md
- services/http-api/package.json
- services/http-api/src/entities/place.ts
- services/http-api/src/routes/cafe/index.test.ts
- services/http-api/src/routes/place/index.test.ts
- services/http-api/src/routes/place/place.control.ts
- services/http-api/src/test/util.ts
- 우선 test로 verify된 feature 이외에 추가된 commit (`2b534b09f6acb474a1282d5151a51059e1df5bc5`) 을 revert합니다. (PR merge 순서 오류)
- 배포 github action script에서 lint error가 발생했습니다. 이는 `@types/koa` 패키지의 업데이트 때문이며 현재 코드에는 버그가 존재하는 것이 맞습니다 :( 우선은 버전을 낮추어 린터를 통과시키고, 버그 수정은 차후 #70 에서 해결할 예정입니다.
> hotfix: build error

- app/package.json
- app/public/index.html
- app/src/components/App.tsx
- app/src/components/Router.tsx
- app/src/hooks/useAnalyticsPageView.ts
- app/src/hooks/useFirebase.ts
- app/src/utils/function.tsx
* `development` / `production` 환경에서 firebase project 분리.
* `development`는 `coffee-hmm-local` 프로젝트로 이벤트가 들어가게 됨 @jyuunnii 초대 보냈으니 확인하세요 :)
* 기존에 SPA라서 page_view 이벤트가 똑바로 잡히지 않는 문제가 있었습니다.
* `react-router`와 연결하여, history가 변경될 때마다 `screen_view` 이벤트를 보내도록 설정했습니다. (`app/src/hooks/useAnalyticsPageView.ts` 참고하세요)
* fixes #91
> Separate firebase project for development/production stage

- app/src/components/common/Header/index.css
- app/src/components/common/Header/index.tsx
- app/src/components/others/CafeByPlace/index.css
- app/src/components/others/CafeByPlace/styled.tsx
- app/src/components/others/CafeDetail/index.css
- app/src/components/others/CafeDetail/index.tsx
- app/src/components/others/CafeDetailImageCarousel/index.css
- app/src/components/others/CarouselDetailImage/index.css
- app/src/components/others/CarouselMainImage/index.css
- app/src/components/others/PositionDotHorizontal/index.tsx
- app/src/components/pages/Detail/index.css
- app/src/index.css
- 디테일 페이지 이미지 하단 index-dot의 초기위치가 가장 마지막(최우측)으로 되어있음
- 헤더가 /header에서 사용되지 않고 디테일 컴포넌트에서 back button이 별개로 활성화 되어 있어 디테일 페이지에서 수정하고 header 복구
- index-dot 초기 위치를 첫번째(최좌측)로 변경 
- 디테일 페이지 이미지 사이즈 width 100%로 변경 (max-height: 360px)
- 컴포넌트 padding 값 수정 및 이에 따른 skeleton 사이즈 조정
> fix: 이미지 사이즈 수정 및 이미지 하단 index-dot 표시 오류 대응

- .github/workflows/ci-jobs.beta.yml
- .github/workflows/ci-jobs.yml
- jobs/package.json
- jobs/serverless.yml
> Jobs CI/CD GitHub Actions 스크립트 작성

- .github/workflows/coverage.yml
- ci/.gitignore
- ci/Makefile
- ci/package.json
- ci/src/type-coverage-codecov.js
- codecov.yml
- CI 시 타입체크 돌도록 스크립트 및 github actions 작성
- Codecov와 integration (PR에 comment 붙여줌)
> Setup type-coverage + codecov integration

- services/http-api/README.md
- services/http-api/src/routes/place/index.test.ts
- services/http-api/src/routes/place/place.control.ts
**AS-IS**
```
{
"place": {
"count": 2,
"list": [
{
"id": "11111111-1111-1111-1111-111111111111",
"createdAt": "2020-01-01T00:00:00.000Z",
"updatedAt": "2020-01-01T00:00:00.000Z",
"name": "판교",
"pinned": true
},
{
"id": "11111111-1111-1111-1111-111111111111",
"createdAt": "2020-01-01T00:00:00.000Z",
"updatedAt": "2020-01-01T00:00:00.000Z",
"name": "연남동",
"pinned": false
}
]
}
}
```
**TO-BE**
```
{
"place": {
"count": 2,
"list": [
{
"id": "11111111-1111-1111-1111-111111111111",
"createdAt": "2020-01-01T00:00:00.000Z",
"updatedAt": "2020-01-01T00:00:00.000Z",
"name": "판교",
"pinned": true,
"cafeCount": 13
},
{
"id": "11111111-1111-1111-1111-111111111111",
"createdAt": "2020-01-01T00:00:00.000Z",
"updatedAt": "2020-01-01T00:00:00.000Z",
"name": "연남동",
"pinned": false,
"cafeCount": 5
}
]
}
} …
```
> GET /place/list 각 place에 cafeCount 필드 추가

- app/package.json
- app/src/components/others/CafeDetailImageCarousel/index.tsx
- app/src/components/others/CafeMainImageCarousel/index.tsx
> release: v2.2.1

- mobile_app/lib/cafe.dart
- mobile_app/lib/cafe_image.dart
- mobile_app/lib/main.dart
- mobile_app/lib/place_list.dart
- mobile_app/lib/type.dart
- 메인 화면 카페 슬라이드 추가
- image 로드 시간 단축 -> 이미지 사이즈 지정 사용으로 대응
- 장소 재선택 시 초기 카페 순서 유지하기 (현재 연남 -> 강남 -> 연남 클릭 시 첫번째와 두번째 연남 카페 리스트 순서 다름)
https://user-images.githubusercontent.com/40883884/126073485-416840fd-ed60-4b5c-9716-4611fdea7f2f.mov
> feat: 메인화면 cafe slider 추가

- mobile_app/.gitignore
- mobile_app/lib/main.dart
> 한 장소에 대해 카페 피드 요청을 최대 1번만 하도록 수정

- mobile_app/lib/api.dart
- mobile_app/lib/main.dart
- mobile_app/lib/main_bottom_sheet.dart
- mobile_app/lib/main_button.dart
- mobile_app/lib/main_page.dart
- mobile_app/lib/main_slider_section.dart
- mobile_app/lib/main_table_section.dart
- 핫플레이스 api 연동
- 카페 클릭 시 디테일 페이지 이동
- 함수명 변경 : `onTapped` -> `onTappedCafe`
> feat: 핫플레이스 api 연동

- mobile_app/android/app/build.gradle
- mobile_app/android/app/src/main/AndroidManifest.xml
- mobile_app/ios/Runner/Info.plist
- mobile_app/lib/detail_button.dart
- mobile_app/lib/detail_page.dart
- mobile_app/lib/main_button.dart
- mobile_app/lib/main_page.dart
- mobile_app/lib/util.dart
- mobile_app/lib/webView.dart
- mobile_app/lib/web_view.dart
- mobile_app/pubspec.lock
- mobile_app/pubspec.yaml
- 네이버 검색, 인스타그램 해시태그 검색 웹뷰로 이동하는 이벤트 추가
- `webview_flutter` 패키지 추가 및 패키지 추가에 따른 설정 코드 수정
https://user-images.githubusercontent.com/40883884/129429488-af221474-0243-45ab-b588-5922a3d1c6ec.mov
> feat: 네이버, 인스타그램 웹뷰 추가

- mobile_app/android/app/src/main/AndroidManifest.xml
- mobile_app/pubspec.lock
- Pub upgrade 
- 안드로이드 permission 추가
- 안드로이드 에뮬레이터에서 설치 및 실행 확인
> feat: 안드로이드release 빌드 세팅 추가

- mobile_app/lib/cafe_image_slider.dart
- mobile_app/lib/detail_page.dart
- mobile_app/lib/main_page.dart
- mobile_app/lib/main_slider_section.dart
- mobile_app/lib/main_table_section.dart
- iOS, android 에서 테이블 모드 시 스크롤 내려가지 않는 이슈
- main_page 의 ListView 제거 후 main_table_section 의 ListView 에 직접 controller 설정
- scrollController, pageController 구분 위해 변수명 변경 
- 아이폰 8, 아이폰 12 미니, 아이패드 테스트 완료
- 안드로이드 에뮬레이터 테스트 완료
> hotfix: 테이블 모드 스크롤 이슈 대응

- mobile_app/lib/cafe_image_slider.dart
- mobile_app/lib/cafe_info.dart
- mobile_app/lib/constants/color.dart
- mobile_app/lib/header.dart
- mobile_app/lib/main_bottom_sheet.dart
- mobile_app/lib/main_button.dart
- mobile_app/lib/main_tab.dart
- mobile_app/lib/main_table_section.dart
- mobile_app/lib/pages/detail_page.dart
- mobile_app/lib/pages/main_page.dart
> feat: Color System

- mobile_app/lib/view/cafe_detail/cafe_detail_info_subway_item.dart
- 지하철 아이콘 추가
- 여백 수정 및 최소 width, height 지정
> fix: 지하철역 메타데이터 디자인 수정

- mobile_app/android/app/src/main/AndroidManifest.xml
- mobile_app/ios/Runner.xcodeproj/project.pbxproj
- mobile_app/ios/Runner/Runner.entitlements
- http(s)://coffeehmm.com/*
- http(s)://www.coffeehmm.com/*
- http(s)://coffee-hmm.inhibitor.io/*
http/https scheme, 3개 도메인에 대해 deep link 설정 추가
- https://coffeehmm.com/*
- https://www.coffeehmm.com/*
- https://coffee-hmm.inhibitor.io/*
위 도메인에 대한 universal link 설정 추가 (홈페이지 쪽에도 작업되어야 하는데, #201 참조)
- https://flutter.dev/docs/development/ui/navigation/deep-linking
- https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html
> 모바일 앱 딥링크 구현

- mobile_app/lib/constants/color.dart
- mobile_app/lib/view/cafe_main/main_button.dart
- mobile_app/lib/view/cafe_main/main_table_section.dart
> fix: design - primary color, background, button color

- mobile_app/lib/main.dart
- iOS
<video src="https://user-images.githubusercontent.com/40883884/148651446-69b94a3e-3598-4d7d-888c-a3255e001fba.mov" />
- AOS
<video src="https://user-images.githubusercontent.com/40883884/148651449-7d6095fd-1ff9-4abd-85cb-a2632461d0be.mov" />
> feat: ios rotate disallowed

- script/Argument.py
- script/Cafe.py
- script/MetaTemplate.py
- script/Place.py
- script/README.md
일단 필요한 것만 만들어봤습니다..
<모든 카페 데이터에 메타데이터 추가하기>
- createMetaTemplate() -> 메타데이터 템플릿 생성
- 템플릿에 직접 메타데이터 json 형식으로 추가
- addAllCafesMeta() 의 inputFile 로 넣어서 실행
> feat: cafe api request script for add metadata

- mobile_app/lib/constants/color.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_info.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_info_subway_item.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_location.dart
- mobile_app/lib/view/cafe_detail/subway_line_badge.dart
- mobile_app/lib/view/cafe_main/main_table_section.dart
- mobile_app/lib/view/common/badge.dart
- mobile_app/lib/view/common/cafe_info_item.dart
- mobile_app/lib/view/common/text_info.dart
리뷰 끝나고 브랜치 바꿔놓겠습니다 release/app/2.3.0 -> release/mobile/1.3.1
- `SubwayLineBadge` 분리
- 팔레트 색상 추가
- `Badge` : size, customSpec 추가
- 여백, 폰트 색상 수정
- 오프라인으로 설명했던 합성 구조로 설계해보겠습니당 !! 💪 -> 어떤 이점이 얼마나 있을까 , 무엇이 확장에 유연한가
> fix: Badge size, customSpec 추가 및 디자인 수정

- mobile_app/lib/view/cafe_detail/cafe_detail_footer.dart
- mobile_app/lib/view/common/button/custom_icon_button.dart
- 카페 상세 페이지 footer 디자인 수정
- `boxShadow` 추가
- 아이콘 버튼 배경 색상 변경
> fix: footer design

- mobile_app/lib/constants/enum.dart
- mobile_app/lib/constants/type.dart
- mobile_app/lib/pages/detail_page.dart
- mobile_app/lib/util/type_transformer.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_body_content.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_footer.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_location.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_menu.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_section_title.dart
- mobile_app/lib/view/common/button/button_size.dart
- mobile_app/lib/view/common/button/custom_button.dart
- mobile_app/lib/view/common/button/custom_icon_button.dart
- mobile_app/pubspec.yaml
- 카페 상세 페이지 메뉴 영역 추가
- 카페 상세 페이지 footer navigation 추가
- 카페 상세 페이지 footer 스타일 수정
> release (mobile_app): 1.3.0

- mobile_app/ios/Runner.xcodeproj/project.pbxproj
- mobile_app/ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
- mobile_app/pubspec.yaml
> release (mobile_app): 1.3.1

- mobile_app/lib/constants/color.dart
- mobile_app/lib/constants/type.dart
- mobile_app/lib/util/cafe_detail.dart
- mobile_app/lib/util/time_formatter.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_info_time_item.dart
- mobile_app/lib/view/common/cafe_operation_status.dart
- 상세 페이지 카페 영업중 / 영업종료 표시
- 시간 메타 정보 유효할 때
- 시간 메타 정보 유효하지 않을 때
- 시간 메타 정보 없을 때
> feat: 상세페이지 카페 영업중/영업종료 표시

- jobs/serverless.cloudfront.yml
- jobs/src/job/appOpenGraph/const.ts
- jobs/src/job/appOpenGraph/originResponse.ts
- jobs/src/job/appOpenGraph/viewerRequest.ts
- jobs/src/services/api/index.ts
> Release: job/appOpenGraph@0.1.0

- mobile_app/lib/router/mixins/enter_cafe_detail_mixin.dart
- mobile_app/lib/view/cafe_main/main_body_content.dart
- mobile_app/lib/view/cafe_main/main_feed_content.dart
- mobile_app/lib/view/cafe_main/main_feed_section.dart
- mobile_app/lib/view/cafe_main/main_slider_section.dart
- Detail 페이지 진입 시에도 currentCafe 상태 업데이트 하여 메인으로 돌아왔을 때 마지막에 머무르던 디테일 페이지의 카페가 보이도록 수정.
> feat: add enterDetail callback to set currentCafe

- mobile_app/lib/constants/color.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_list_item.dart
- mobile_app/lib/view/cafe_main/main_tab.dart
- mobile_app/lib/view/common/button/custom_button.dart
- mobile_app/lib/view/common/button/custom_icon_button.dart
- flutter 버전 업그레이드에 따른 디자인 이슈 대응
- `elevation: 0` 추가
- `custom_icon_button` : 상세 푸터 아이콘 버튼 클릭 시 overlayColor 옵션 추가
https://user-images.githubusercontent.com/40883884/158733166-24b50110-915b-4bc6-a8dc-fce0c21830a6.mov
> feat: add icon button overlayColor

- mobile_app/lib/view/common/cafe_image.dart
> fix: remove main image resizing

- mobile_app/lib/constants/color.dart
- mobile_app/lib/router/mixins/enter_cafe_detail_mixin.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_list_item.dart
- mobile_app/lib/view/cafe_main/main_body_content.dart
- mobile_app/lib/view/cafe_main/main_feed_content.dart
- mobile_app/lib/view/cafe_main/main_feed_section.dart
- mobile_app/lib/view/cafe_main/main_slider_section.dart
- mobile_app/lib/view/cafe_main/main_tab.dart
- mobile_app/lib/view/common/button/custom_button.dart
- mobile_app/lib/view/common/button/custom_icon_button.dart
- mobile_app/lib/view/common/cafe_image.dart
- mobile_app/pubspec.yaml
- enterDetail setCurrentCafe callback 추가
- 메인 이미지 resizing 미적용
- 디자인 수정
- flutter SDK version upgrade design crash 대응 
- detail footer icon button 클릭 시 효과 추가
> release (mobile_app): 1.4.1+14

- mobile_app/lib/constants/color.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_body_content.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_footer.dart
- mobile_app/lib/view/common/button/custom_icon_button.dart
- mobile_app/pubspec.yaml
- 디테일 페이지 footer 동작 수정
- as-is : 사용자 스크롤 offset 만큼 점진적 노출 
- to-be : 사용자 스크롤 발생 시 노출/숨김
> release (mobile_app): 1.4.1+15

- mobile_app/ios/Podfile.lock
- mobile_app/lib/constants/type.dart
- mobile_app/lib/pages/saved_page.dart
- mobile_app/lib/router/app_route_information_parser.dart
- mobile_app/lib/router/app_router_delegate.dart
- mobile_app/lib/router/app_state.dart
- mobile_app/lib/router/mixins/enter_cafe_detail_mixin.dart
- mobile_app/lib/router/mixins/enter_saved_mixin.dart
- mobile_app/lib/router/mixins/enter_settings_mixin.dart
- mobile_app/lib/router/page_configuration.dart
- mobile_app/lib/router/pages.dart
- mobile_app/lib/storage/cafe.dart
- mobile_app/lib/storage/model/cafe.dart
- mobile_app/lib/view/cafe_detail/cafe_detail_body_content.dart
- mobile_app/lib/view/cafe_main/main_bottom_sheet.dart
- mobile_app/lib/view/cafe_main/main_feed_content.dart
- mobile_app/lib/view/cafe_main/main_slider_section.dart
- mobile_app/lib/view/common/button/custom_icon_button.dart
- mobile_app/lib/view/common/header.dart
- mobile_app/lib/view/saved/saved_body_content.dart
- mobile_app/lib/view/saved/saved_element.dart
- mobile_app/pubspec.lock
- mobile_app/pubspec.yaml
- 카페 저장하기 기능 추가
- C/R/D
- 저장 타입 : String
- 저장 단위 : CafeModel 에서 메타데이터(optional field)만 제외하고 저장
- saved_page 에서 기본 정보 외에 이미지, 장소 정보 등을 사용할 가능성이 있다고 판단하여 CafeModel 단위로 저장했습니다. 메타데이터 사용 계획은 빠른 시일 내에는 없음.
- 저장 단위에 따른  toJson static method 추가
- 플러그인 : [shared_preference](https://pub.dev/packages/shared_preferences)
- saved_page 페이지 추가 및 라우팅 설정
- 디테일 페이지에서 카페 저장 : C, R, D 사용
- enterCafeDetail param 변경 : CafeModel -> String
- saved_page body : R, D 사용
> feat: add save-cafe function and saved page
